[package]
name = "truss"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1" }
bevy_cursor = {version= "0.6.0", features=["2d"]}
faer = "0.23.2"
nalgebra = "0.34.1"
rayon = "1.11.0"
serde = "1.0.228"
serde_json = "1.0.145"
